# Uncomment the next line to define a global platform for your project

source "https://github.com/CocoaPods/Specs.git"
source "https://github.com/livekit/podspecs.git"

use_frameworks! :linkage => :static

target 'using-cocoapods (iOS)' do

  platform :ios, '13.0'

  # Pods for using-cocoapods (iOS)
  pod 'LiveKitClient', '2.8.1'
end

target 'using-cocoapods (macOS)' do
  
  platform :macos, '12.3'

  # Pods for using-cocoapods (macOS)
  pod 'LiveKitClient', '2.8.1'
end
